/*
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  
 *  Copyright 2012  SOARS Project.
 *  <author> Hiroshi Deguchi(SOARS Project.)
 *  <author> Yasunari Ishizuka(PieCake.inc,)
 */
/*
 * @(#)DtAlgeSetIOTestHelper.java	1.70	2012/05/30
 *     - created by Y.Ishizuka(PieCake.inc,)
 */
package ssac.aadl.runtime;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collection;

import dtalge.DtAlgeSet;
import dtalge.DtBase;
import dtalge.Dtalge;

public class DtAlgeSetIOTestHelper
{
	//------------------------------------------------------------
	// Constants
	//------------------------------------------------------------
	// テストデータの全基底集合(整列済み)
	static public final DtBase[] sortedAllBaseSetData =
	{
		new DtBase("基底01", "string" , "#", "#"),
		new DtBase("基底01", "decimal", "#", "#"),
		new DtBase("基底01", "boolean", "#", "#"),
		new DtBase("基底02", "string" , "#", "#"),
		new DtBase("基底02", "decimal", "#", "#"),
		new DtBase("基底02", "boolean", "#", "#"),
		new DtBase("基底03", "string" , "#", "#"),
		new DtBase("基底03", "decimal", "#", "#"),
		new DtBase("基底03", "boolean", "#", "#"),
		new DtBase("基底04", "string" , "#", "#"),
		new DtBase("基底04", "decimal", "#", "#"),
		new DtBase("基底04", "boolean", "#", "#"),
		new DtBase("基底05", "string" , "#", "#"),
		new DtBase("基底05", "decimal", "#", "#"),
		new DtBase("基底05", "boolean", "#", "#"),
		new DtBase("基底06", "string" , "#", "#"),
		new DtBase("基底06", "decimal", "#", "#"),
		new DtBase("基底06", "boolean", "#", "#"),
		new DtBase("基底07", "string" , "#", "#"),
		new DtBase("基底07", "decimal", "#", "#"),
		new DtBase("基底07", "boolean", "#", "#"),
		new DtBase("基底08", "string" , "#", "#"),
		new DtBase("基底08", "decimal", "#", "#"),
		new DtBase("基底08", "boolean", "#", "#"),
		new DtBase("基底09", "string" , "#", "#"),
		new DtBase("基底09", "decimal", "#", "#"),
		new DtBase("基底09", "boolean", "#", "#"),
		new DtBase("基底0a", "string" , "#", "#"),
		new DtBase("基底0a", "decimal", "#", "#"),
		new DtBase("基底0a", "boolean", "#", "#"),
		new DtBase("基底0b", "string" , "#", "#"),
		new DtBase("基底0b", "decimal", "#", "#"),
		new DtBase("基底0b", "boolean", "#", "#"),
		new DtBase("基底0c", "string" , "#", "#"),
		new DtBase("基底0c", "decimal", "#", "#"),
		new DtBase("基底0c", "boolean", "#", "#"),
		new DtBase("基底0d", "string" , "#", "#"),
		new DtBase("基底0d", "decimal", "#", "#"),
		new DtBase("基底0d", "boolean", "#", "#"),
	};
	
	// テストデータの部分基底集合(整列済み)
	static public final DtBase[] halfSortedAllBaseSetData =
	{
		new DtBase("基底01", "string" , "#", "#"),
		new DtBase("基底01", "decimal", "#", "#"),
		new DtBase("基底01", "boolean", "#", "#"),
		new DtBase("基底02", "string" , "#", "#"),
		new DtBase("基底02", "decimal", "#", "#"),
		new DtBase("基底02", "boolean", "#", "#"),
		new DtBase("基底03", "string" , "#", "#"),
		new DtBase("基底03", "decimal", "#", "#"),
		new DtBase("基底03", "boolean", "#", "#"),
		new DtBase("基底04", "string" , "#", "#"),
		new DtBase("基底04", "decimal", "#", "#"),
		new DtBase("基底04", "boolean", "#", "#"),
		new DtBase("基底05", "string" , "#", "#"),
		new DtBase("基底05", "decimal", "#", "#"),
		new DtBase("基底05", "boolean", "#", "#"),
		new DtBase("基底06", "string" , "#", "#"),
		new DtBase("基底06", "decimal", "#", "#"),
		new DtBase("基底06", "boolean", "#", "#"),
		new DtBase("基底07", "string" , "#", "#"),
		new DtBase("基底07", "decimal", "#", "#"),
		new DtBase("基底07", "boolean", "#", "#"),
		new DtBase("基底08", "string" , "#", "#"),
		new DtBase("基底08", "decimal", "#", "#"),
		new DtBase("基底08", "boolean", "#", "#"),
		new DtBase("基底09", "string" , "#", "#"),
		new DtBase("基底09", "decimal", "#", "#"),
		new DtBase("基底09", "boolean", "#", "#"),
	};

	// 基準となるテストデータ(空文字列も含む)
	static public final Object[][] sortedAllAlgeSetData =
	{
		{
			new DtBase("基底01", "string" , "#", "#"), "文字列01",
			new DtBase("基底01", "decimal", "#", "#"), new BigDecimal("-0.01"),
			new DtBase("基底01", "boolean", "#", "#"), true,
			new DtBase("基底02", "string" , "#", "#"), "!%!%!%文字列02",
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("123.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底03", "string" , "#", "#"), "文字列03",
			new DtBase("基底03", "decimal", "#", "#"), new BigDecimal("10.03"),
			new DtBase("基底03", "boolean", "#", "#"), true,
			new DtBase("基底04", "string" , "#", "#"), "文字列!%04",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-975.04"),
			new DtBase("基底04", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), "文字列05",
			new DtBase("基底05", "decimal", "#", "#"), new BigDecimal("2345.05"),
			new DtBase("基底05", "boolean", "#", "#"), true,
			new DtBase("基底06", "string" , "#", "#"), " !%文字列06",
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("-1006"),
			new DtBase("基底06", "boolean", "#", "#"), false,
			new DtBase("基底07", "string" , "#", "#"), "文字列07",
			new DtBase("基底07", "decimal", "#", "#"), new BigDecimal("513534321207"),
			new DtBase("基底07", "boolean", "#", "#"), true,
			new DtBase("基底08", "string" , "#", "#"), "文字列08",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-0.2108"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底09", "string" , "#", "#"), "文字列09",
			new DtBase("基底09", "decimal", "#", "#"), new BigDecimal("0.109"),
			new DtBase("基底09", "boolean", "#", "#"), true,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
			new DtBase("基底0b", "string" , "#", "#"), "",
			new DtBase("基底0b", "decimal", "#", "#"), BigDecimal.ZERO,
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底0c", "string" , "#", "#"), "!%n",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("1.12"),
			new DtBase("基底0c", "boolean", "#", "#"), true,
			new DtBase("基底0d", "string" , "#", "#"), "!%",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底01", "string" , "#", "#"), "文字列11",
			new DtBase("基底01", "decimal", "#", "#"), new BigDecimal("1.01"),
			new DtBase("基底01", "boolean", "#", "#"), false,
			new DtBase("基底02", "string" , "#", "#"), "文字列12",
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("1.02"),
			new DtBase("基底02", "boolean", "#", "#"), true,
			new DtBase("基底03", "string" , "#", "#"), "文字列13",
			new DtBase("基底03", "decimal", "#", "#"), new BigDecimal("1.03"),
			new DtBase("基底03", "boolean", "#", "#"), false,
			new DtBase("基底04", "string" , "#", "#"), "文字列14",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("1.04"),
			new DtBase("基底04", "boolean", "#", "#"), true,
			new DtBase("基底05", "string" , "#", "#"), "文字列15",
			new DtBase("基底05", "decimal", "#", "#"), new BigDecimal("1.05"),
			new DtBase("基底05", "boolean", "#", "#"), false,
			new DtBase("基底06", "string" , "#", "#"), "文字列16",
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("1.06"),
			new DtBase("基底06", "boolean", "#", "#"), true,
			new DtBase("基底07", "string" , "#", "#"), "文字列17",
			new DtBase("基底07", "decimal", "#", "#"), new BigDecimal("1.07"),
			new DtBase("基底07", "boolean", "#", "#"), false,
			new DtBase("基底08", "string" , "#", "#"), "文字列18",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("1.08"),
			new DtBase("基底08", "boolean", "#", "#"), true,
			new DtBase("基底09", "string" , "#", "#"), "文字列19",
			new DtBase("基底09", "decimal", "#", "#"), new BigDecimal("1.09"),
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), "文字列1a",
			new DtBase("基底0a", "decimal", "#", "#"), new BigDecimal("1.10"),
			new DtBase("基底0a", "boolean", "#", "#"), true,
			new DtBase("基底0b", "string" , "#", "#"), "!%",
			new DtBase("基底0b", "decimal", "#", "#"), new BigDecimal("1.11"),
			new DtBase("基底0b", "boolean", "#", "#"), true,
			new DtBase("基底0c", "string" , "#", "#"), "!%文字列1c",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("1.12"),
			new DtBase("基底0c", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%!%文字列1d",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), true,
		},
		{
			new DtBase("基底01", "string" , "#", "#"), "文字列21",
			new DtBase("基底01", "decimal", "#", "#"), new BigDecimal("-2.01"),
			new DtBase("基底01", "boolean", "#", "#"), true,
			new DtBase("基底02", "string" , "#", "#"), "文字列22",
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("-2.02"),
			new DtBase("基底02", "boolean", "#", "#"), true,
			new DtBase("基底03", "string" , "#", "#"), "文字列23",
			new DtBase("基底03", "decimal", "#", "#"), new BigDecimal("-2.03"),
			new DtBase("基底03", "boolean", "#", "#"), true,
			new DtBase("基底04", "string" , "#", "#"), " !%文字列24",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-2.04"),
			new DtBase("基底04", "boolean", "#", "#"), true,
			new DtBase("基底05", "string" , "#", "#"), "文字列25",
			new DtBase("基底05", "decimal", "#", "#"), new BigDecimal("-2.05"),
			new DtBase("基底05", "boolean", "#", "#"), false,
			new DtBase("基底06", "string" , "#", "#"), "文字列26",
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("-2.06"),
			new DtBase("基底06", "boolean", "#", "#"), false,
			new DtBase("基底07", "string" , "#", "#"), "文字列!%27",
			new DtBase("基底07", "decimal", "#", "#"), new BigDecimal("-2.07"),
			new DtBase("基底07", "boolean", "#", "#"), false,
			new DtBase("基底08", "string" , "#", "#"), "文字列28",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-2.08"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底09", "string" , "#", "#"), "文字列29",
			new DtBase("基底09", "decimal", "#", "#"), new BigDecimal("-2.09"),
			new DtBase("基底09", "boolean", "#", "#"), true,
			new DtBase("基底0a", "string" , "#", "#"), "文字列2a",
			new DtBase("基底0a", "decimal", "#", "#"), new BigDecimal("-2.10"),
			new DtBase("基底0a", "boolean", "#", "#"), true,
			new DtBase("基底0b", "string" , "#", "#"), "文字列2b",
			new DtBase("基底0b", "decimal", "#", "#"), new BigDecimal("-2.11"),
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底0c", "string" , "#", "#"), "!%文字列2c",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("-2.12"),
			new DtBase("基底0c", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%!%文字列2d",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-2.13"),
			new DtBase("基底0d", "boolean", "#", "#"), null,
		},
		{
			new DtBase("基底01", "string" , "#", "#"), null,
			new DtBase("基底01", "decimal", "#", "#"), new BigDecimal("3.01"),
			new DtBase("基底01", "boolean", "#", "#"), false,
			new DtBase("基底02", "string" , "#", "#"), null,
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("3.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底03", "string" , "#", "#"), null,
			new DtBase("基底03", "decimal", "#", "#"), new BigDecimal("3.03"),
			new DtBase("基底03", "boolean", "#", "#"), false,
			new DtBase("基底04", "string" , "#", "#"), null,
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("3.04"),
			new DtBase("基底04", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), null,
			new DtBase("基底05", "decimal", "#", "#"), new BigDecimal("3.05"),
			new DtBase("基底05", "boolean", "#", "#"), true,
			new DtBase("基底06", "string" , "#", "#"), null,
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("3.06"),
			new DtBase("基底06", "boolean", "#", "#"), true,
			new DtBase("基底07", "string" , "#", "#"), null,
			new DtBase("基底07", "decimal", "#", "#"), new BigDecimal("3.07"),
			new DtBase("基底07", "boolean", "#", "#"), true,
			new DtBase("基底08", "string" , "#", "#"), null,
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("3.08"),
			new DtBase("基底08", "boolean", "#", "#"), true,
			new DtBase("基底09", "string" , "#", "#"), null,
			new DtBase("基底09", "decimal", "#", "#"), new BigDecimal("3.09"),
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), new BigDecimal("3.10"),
			new DtBase("基底0a", "boolean", "#", "#"), false,
			new DtBase("基底0b", "string" , "#", "#"), null,
			new DtBase("基底0b", "decimal", "#", "#"), new BigDecimal("3.11"),
			new DtBase("基底0b", "boolean", "#", "#"), true,
			new DtBase("基底0c", "string" , "#", "#"), null,
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("3.12"),
			new DtBase("基底0c", "boolean", "#", "#"), true,
			new DtBase("基底0d", "string" , "#", "#"), null,
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("3.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底01", "string" , "#", "#"), "文字列41",
			new DtBase("基底01", "decimal", "#", "#"), null,
			new DtBase("基底01", "boolean", "#", "#"), false,
			new DtBase("基底02", "string" , "#", "#"), "文字列42",
			new DtBase("基底02", "decimal", "#", "#"), null,
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底03", "string" , "#", "#"), "文字列43",
			new DtBase("基底03", "decimal", "#", "#"), null,
			new DtBase("基底03", "boolean", "#", "#"), true,
			new DtBase("基底04", "string" , "#", "#"), "文字列44",
			new DtBase("基底04", "decimal", "#", "#"), null,
			new DtBase("基底04", "boolean", "#", "#"), true,
			new DtBase("基底05", "string" , "#", "#"), "文字列45",
			new DtBase("基底05", "decimal", "#", "#"), null,
			new DtBase("基底05", "boolean", "#", "#"), false,
			new DtBase("基底06", "string" , "#", "#"), "文字列46",
			new DtBase("基底06", "decimal", "#", "#"), null,
			new DtBase("基底06", "boolean", "#", "#"), false,
			new DtBase("基底07", "string" , "#", "#"), "文字列47",
			new DtBase("基底07", "decimal", "#", "#"), null,
			new DtBase("基底07", "boolean", "#", "#"), true,
			new DtBase("基底08", "string" , "#", "#"), "文字列48",
			new DtBase("基底08", "decimal", "#", "#"), null,
			new DtBase("基底08", "boolean", "#", "#"), true,
			new DtBase("基底09", "string" , "#", "#"), "文字列49",
			new DtBase("基底09", "decimal", "#", "#"), null,
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), "文字列4a",
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), false,
			new DtBase("基底0b", "string" , "#", "#"), "文字列4b",
			new DtBase("基底0b", "decimal", "#", "#"), null,
			new DtBase("基底0b", "boolean", "#", "#"), true,
			new DtBase("基底0c", "string" , "#", "#"), "!%文字列4c",
			new DtBase("基底0c", "decimal", "#", "#"), null,
			new DtBase("基底0c", "boolean", "#", "#"), true,
			new DtBase("基底0d", "string" , "#", "#"), "!%!%文字列4d",
			new DtBase("基底0d", "decimal", "#", "#"), null,
			new DtBase("基底0d", "boolean", "#", "#"), true,
		},
		{
			new DtBase("基底01", "string" , "#", "#"), null,
			new DtBase("基底01", "decimal", "#", "#"), null,
			new DtBase("基底01", "boolean", "#", "#"), null,
			new DtBase("基底02", "string" , "#", "#"), null,
			new DtBase("基底02", "decimal", "#", "#"), null,
			new DtBase("基底02", "boolean", "#", "#"), null,
			new DtBase("基底03", "string" , "#", "#"), null,
			new DtBase("基底03", "decimal", "#", "#"), null,
			new DtBase("基底03", "boolean", "#", "#"), null,
			new DtBase("基底04", "string" , "#", "#"), null,
			new DtBase("基底04", "decimal", "#", "#"), null,
			new DtBase("基底04", "boolean", "#", "#"), null,
			new DtBase("基底05", "string" , "#", "#"), null,
			new DtBase("基底05", "decimal", "#", "#"), null,
			new DtBase("基底05", "boolean", "#", "#"), null,
			new DtBase("基底06", "string" , "#", "#"), null,
			new DtBase("基底06", "decimal", "#", "#"), null,
			new DtBase("基底06", "boolean", "#", "#"), null,
			new DtBase("基底07", "string" , "#", "#"), null,
			new DtBase("基底07", "decimal", "#", "#"), null,
			new DtBase("基底07", "boolean", "#", "#"), null,
			new DtBase("基底08", "string" , "#", "#"), null,
			new DtBase("基底08", "decimal", "#", "#"), null,
			new DtBase("基底08", "boolean", "#", "#"), null,
			new DtBase("基底09", "string" , "#", "#"), null,
			new DtBase("基底09", "decimal", "#", "#"), null,
			new DtBase("基底09", "boolean", "#", "#"), null,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
			new DtBase("基底0b", "string" , "#", "#"), null,
			new DtBase("基底0b", "decimal", "#", "#"), null,
			new DtBase("基底0b", "boolean", "#", "#"), null,
			new DtBase("基底0c", "string" , "#", "#"), null,
			new DtBase("基底0c", "decimal", "#", "#"), null,
			new DtBase("基底0c", "boolean", "#", "#"), null,
			new DtBase("基底0d", "string" , "#", "#"), null,
			new DtBase("基底0d", "decimal", "#", "#"), null,
			new DtBase("基底0d", "boolean", "#", "#"), null,
		},
		{
			new DtBase("基底01", "string" , "#", "#"), "文字列01",
			new DtBase("基底01", "decimal", "#", "#"), new BigDecimal("-0.01"),
			new DtBase("基底01", "boolean", "#", "#"), true,
			new DtBase("基底02", "string" , "#", "#"), "!%!%!%文字列02",
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("123.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底03", "string" , "#", "#"), "文字列03",
			new DtBase("基底03", "decimal", "#", "#"), new BigDecimal("10.03"),
			new DtBase("基底03", "boolean", "#", "#"), true,
			new DtBase("基底04", "string" , "#", "#"), "文字列!%04",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-975.04"),
			new DtBase("基底04", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), "文字列05",
			new DtBase("基底05", "decimal", "#", "#"), new BigDecimal("2345.05"),
			new DtBase("基底05", "boolean", "#", "#"), true,
			new DtBase("基底06", "string" , "#", "#"), " !%文字列06",
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("-1006"),
			new DtBase("基底06", "boolean", "#", "#"), false,
			new DtBase("基底07", "string" , "#", "#"), "文字列07",
			new DtBase("基底07", "decimal", "#", "#"), new BigDecimal("513534321207"),
			new DtBase("基底07", "boolean", "#", "#"), true,
			new DtBase("基底08", "string" , "#", "#"), "文字列08",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-0.2108"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底09", "string" , "#", "#"), "文字列09",
			new DtBase("基底09", "decimal", "#", "#"), new BigDecimal("0.109"),
			new DtBase("基底09", "boolean", "#", "#"), true,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
			new DtBase("基底0b", "string" , "#", "#"), "",
			new DtBase("基底0b", "decimal", "#", "#"), BigDecimal.ZERO,
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底0c", "string" , "#", "#"), "!%n",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("1.12"),
			new DtBase("基底0c", "boolean", "#", "#"), true,
			new DtBase("基底0d", "string" , "#", "#"), "!%",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
		},
	};

	// 書き込み用ランダム順序のテストデータ(空文字列も含む)
	static public final Object[][] writeRandomAlgeSetData =
	{
		{
			new DtBase("基底08", "string" , "#", "#"), "文字列08",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-0.2108"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底02", "string" , "#", "#"), "!%!%!%文字列02",
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("123.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
			new DtBase("基底06", "string" , "#", "#"), " !%文字列06",
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("-1006"),
			new DtBase("基底06", "boolean", "#", "#"), false,
			new DtBase("基底04", "string" , "#", "#"), "文字列!%04",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-975.04"),
			new DtBase("基底04", "boolean", "#", "#"), false,
			new DtBase("基底0c", "string" , "#", "#"), "!%n",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("1.12"),
			new DtBase("基底0c", "boolean", "#", "#"), true,
			new DtBase("基底0b", "string" , "#", "#"), "",
			new DtBase("基底0b", "decimal", "#", "#"), BigDecimal.ZERO,
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
		},
		{
			new DtBase("基底0d", "string" , "#", "#"), "!%!%文字列1d",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), true,
			new DtBase("基底03", "string" , "#", "#"), "文字列13",
			new DtBase("基底03", "decimal", "#", "#"), new BigDecimal("1.03"),
			new DtBase("基底03", "boolean", "#", "#"), false,
			new DtBase("基底09", "string" , "#", "#"), "文字列19",
			new DtBase("基底09", "decimal", "#", "#"), new BigDecimal("1.09"),
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底07", "string" , "#", "#"), "文字列17",
			new DtBase("基底07", "decimal", "#", "#"), new BigDecimal("1.07"),
			new DtBase("基底07", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), "文字列15",
			new DtBase("基底05", "decimal", "#", "#"), new BigDecimal("1.05"),
			new DtBase("基底05", "boolean", "#", "#"), false,
			new DtBase("基底0b", "string" , "#", "#"), "!%",
			new DtBase("基底0b", "decimal", "#", "#"), new BigDecimal("1.11"),
			new DtBase("基底0b", "boolean", "#", "#"), true,
			new DtBase("基底01", "string" , "#", "#"), "文字列11",
			new DtBase("基底01", "decimal", "#", "#"), new BigDecimal("1.01"),
			new DtBase("基底01", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底03", "boolean", "#", "#"), true,
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-2.13"),
			new DtBase("基底03", "decimal", "#", "#"), new BigDecimal("-2.03"),
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-2.08"),
			new DtBase("基底0d", "boolean", "#", "#"), null,
			new DtBase("基底04", "string" , "#", "#"), " !%文字列24",
			new DtBase("基底0b", "decimal", "#", "#"), new BigDecimal("-2.11"),
			new DtBase("基底07", "boolean", "#", "#"), false,
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("-2.12"),
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-2.04"),
			new DtBase("基底04", "boolean", "#", "#"), true,
			new DtBase("基底07", "string" , "#", "#"), "文字列!%27",
			new DtBase("基底08", "string" , "#", "#"), "文字列28",
			new DtBase("基底03", "string" , "#", "#"), "文字列23",
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底0b", "string" , "#", "#"), "文字列2b",
			new DtBase("基底0c", "string" , "#", "#"), "!%文字列2c",
			new DtBase("基底07", "decimal", "#", "#"), new BigDecimal("-2.07"),
			new DtBase("基底0c", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%!%文字列2d",
		},
		{
			new DtBase("基底01", "string" , "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), false,
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底05", "decimal", "#", "#"), new BigDecimal("3.05"),
			new DtBase("基底05", "boolean", "#", "#"), true,
			new DtBase("基底09", "decimal", "#", "#"), new BigDecimal("3.09"),
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底01", "boolean", "#", "#"), false,
			new DtBase("基底02", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), new BigDecimal("3.10"),
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("3.02"),
			new DtBase("基底0d", "string" , "#", "#"), null,
			new DtBase("基底06", "string" , "#", "#"), null,
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("3.06"),
			new DtBase("基底06", "boolean", "#", "#"), true,
			new DtBase("基底09", "string" , "#", "#"), null,
			new DtBase("基底05", "string" , "#", "#"), null,
			new DtBase("基底01", "decimal", "#", "#"), new BigDecimal("3.01"),
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("3.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底05", "decimal", "#", "#"), null,
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), "文字列45",
			new DtBase("基底05", "boolean", "#", "#"), false,
			new DtBase("基底02", "string" , "#", "#"), "文字列42",
			new DtBase("基底09", "string" , "#", "#"), "文字列49",
			new DtBase("基底02", "decimal", "#", "#"), null,
			new DtBase("基底09", "decimal", "#", "#"), null,
		},
		{
			new DtBase("基底01", "decimal", "#", "#"), null,
			new DtBase("基底0b", "boolean", "#", "#"), null,
			new DtBase("基底0d", "string" , "#", "#"), null,
			new DtBase("基底03", "decimal", "#", "#"), null,
			new DtBase("基底08", "boolean", "#", "#"), null,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底03", "boolean", "#", "#"), null,
			new DtBase("基底07", "string" , "#", "#"), null,
			new DtBase("基底03", "string" , "#", "#"), null,
			new DtBase("基底07", "decimal", "#", "#"), null,
			new DtBase("基底08", "decimal", "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
			new DtBase("基底0b", "string" , "#", "#"), null,
			new DtBase("基底01", "boolean", "#", "#"), null,
			new DtBase("基底07", "boolean", "#", "#"), null,
			new DtBase("基底08", "string" , "#", "#"), null,
			new DtBase("基底0b", "decimal", "#", "#"), null,
			new DtBase("基底0d", "decimal", "#", "#"), null,
			new DtBase("基底0d", "boolean", "#", "#"), null,
			new DtBase("基底01", "string" , "#", "#"), null,
		},
		{
			new DtBase("基底08", "string" , "#", "#"), "文字列08",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-0.2108"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底02", "string" , "#", "#"), "!%!%!%文字列02",
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("123.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
			new DtBase("基底06", "string" , "#", "#"), " !%文字列06",
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("-1006"),
			new DtBase("基底06", "boolean", "#", "#"), false,
			new DtBase("基底04", "string" , "#", "#"), "文字列!%04",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-975.04"),
			new DtBase("基底04", "boolean", "#", "#"), false,
			new DtBase("基底0c", "string" , "#", "#"), "!%n",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("1.12"),
			new DtBase("基底0c", "boolean", "#", "#"), true,
			new DtBase("基底0b", "string" , "#", "#"), "",
			new DtBase("基底0b", "decimal", "#", "#"), BigDecimal.ZERO,
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
		},
	};

	// 読み込み用ランダム順序のテストデータ(空文字列はnull)
	static public final Object[][] readRandomAlgeSetData =
	{
		{
			new DtBase("基底08", "string" , "#", "#"), "文字列08",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-0.2108"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底02", "string" , "#", "#"), "!%!%!%文字列02",
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("123.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
			new DtBase("基底06", "string" , "#", "#"), " !%文字列06",
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("-1006"),
			new DtBase("基底06", "boolean", "#", "#"), false,
			new DtBase("基底04", "string" , "#", "#"), "文字列!%04",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-975.04"),
			new DtBase("基底04", "boolean", "#", "#"), false,
			new DtBase("基底0c", "string" , "#", "#"), "!%n",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("1.12"),
			new DtBase("基底0c", "boolean", "#", "#"), true,
			new DtBase("基底0b", "string" , "#", "#"), null,
			new DtBase("基底0b", "decimal", "#", "#"), BigDecimal.ZERO,
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
		},
		{
			new DtBase("基底0d", "string" , "#", "#"), "!%!%文字列1d",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), true,
			new DtBase("基底03", "string" , "#", "#"), "文字列13",
			new DtBase("基底03", "decimal", "#", "#"), new BigDecimal("1.03"),
			new DtBase("基底03", "boolean", "#", "#"), false,
			new DtBase("基底09", "string" , "#", "#"), "文字列19",
			new DtBase("基底09", "decimal", "#", "#"), new BigDecimal("1.09"),
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底07", "string" , "#", "#"), "文字列17",
			new DtBase("基底07", "decimal", "#", "#"), new BigDecimal("1.07"),
			new DtBase("基底07", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), "文字列15",
			new DtBase("基底05", "decimal", "#", "#"), new BigDecimal("1.05"),
			new DtBase("基底05", "boolean", "#", "#"), false,
			new DtBase("基底0b", "string" , "#", "#"), "!%",
			new DtBase("基底0b", "decimal", "#", "#"), new BigDecimal("1.11"),
			new DtBase("基底0b", "boolean", "#", "#"), true,
			new DtBase("基底01", "string" , "#", "#"), "文字列11",
			new DtBase("基底01", "decimal", "#", "#"), new BigDecimal("1.01"),
			new DtBase("基底01", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底03", "boolean", "#", "#"), true,
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-2.13"),
			new DtBase("基底03", "decimal", "#", "#"), new BigDecimal("-2.03"),
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-2.08"),
			new DtBase("基底0d", "boolean", "#", "#"), null,
			new DtBase("基底04", "string" , "#", "#"), " !%文字列24",
			new DtBase("基底0b", "decimal", "#", "#"), new BigDecimal("-2.11"),
			new DtBase("基底07", "boolean", "#", "#"), false,
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("-2.12"),
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-2.04"),
			new DtBase("基底04", "boolean", "#", "#"), true,
			new DtBase("基底07", "string" , "#", "#"), "文字列!%27",
			new DtBase("基底08", "string" , "#", "#"), "文字列28",
			new DtBase("基底03", "string" , "#", "#"), "文字列23",
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底0b", "string" , "#", "#"), "文字列2b",
			new DtBase("基底0c", "string" , "#", "#"), "!%文字列2c",
			new DtBase("基底07", "decimal", "#", "#"), new BigDecimal("-2.07"),
			new DtBase("基底0c", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%!%文字列2d",
		},
		{
			new DtBase("基底01", "string" , "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), false,
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底05", "decimal", "#", "#"), new BigDecimal("3.05"),
			new DtBase("基底05", "boolean", "#", "#"), true,
			new DtBase("基底09", "decimal", "#", "#"), new BigDecimal("3.09"),
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底01", "boolean", "#", "#"), false,
			new DtBase("基底02", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), new BigDecimal("3.10"),
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("3.02"),
			new DtBase("基底0d", "string" , "#", "#"), null,
			new DtBase("基底06", "string" , "#", "#"), null,
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("3.06"),
			new DtBase("基底06", "boolean", "#", "#"), true,
			new DtBase("基底09", "string" , "#", "#"), null,
			new DtBase("基底05", "string" , "#", "#"), null,
			new DtBase("基底01", "decimal", "#", "#"), new BigDecimal("3.01"),
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("3.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底05", "decimal", "#", "#"), null,
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), "文字列45",
			new DtBase("基底05", "boolean", "#", "#"), false,
			new DtBase("基底02", "string" , "#", "#"), "文字列42",
			new DtBase("基底09", "string" , "#", "#"), "文字列49",
			new DtBase("基底02", "decimal", "#", "#"), null,
			new DtBase("基底09", "decimal", "#", "#"), null,
		},
		{
			new DtBase("基底01", "decimal", "#", "#"), null,
			new DtBase("基底0b", "boolean", "#", "#"), null,
			new DtBase("基底0d", "string" , "#", "#"), null,
			new DtBase("基底03", "decimal", "#", "#"), null,
			new DtBase("基底08", "boolean", "#", "#"), null,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底03", "boolean", "#", "#"), null,
			new DtBase("基底07", "string" , "#", "#"), null,
			new DtBase("基底03", "string" , "#", "#"), null,
			new DtBase("基底07", "decimal", "#", "#"), null,
			new DtBase("基底08", "decimal", "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
			new DtBase("基底0b", "string" , "#", "#"), null,
			new DtBase("基底01", "boolean", "#", "#"), null,
			new DtBase("基底07", "boolean", "#", "#"), null,
			new DtBase("基底08", "string" , "#", "#"), null,
			new DtBase("基底0b", "decimal", "#", "#"), null,
			new DtBase("基底0d", "decimal", "#", "#"), null,
			new DtBase("基底0d", "boolean", "#", "#"), null,
			new DtBase("基底01", "string" , "#", "#"), null,
		},
		{
			new DtBase("基底08", "string" , "#", "#"), "文字列08",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-0.2108"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底02", "string" , "#", "#"), "!%!%!%文字列02",
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("123.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
			new DtBase("基底06", "string" , "#", "#"), " !%文字列06",
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("-1006"),
			new DtBase("基底06", "boolean", "#", "#"), false,
			new DtBase("基底04", "string" , "#", "#"), "文字列!%04",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-975.04"),
			new DtBase("基底04", "boolean", "#", "#"), false,
			new DtBase("基底0c", "string" , "#", "#"), "!%n",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("1.12"),
			new DtBase("基底0c", "boolean", "#", "#"), true,
			new DtBase("基底0b", "string" , "#", "#"), null,
			new DtBase("基底0b", "decimal", "#", "#"), BigDecimal.ZERO,
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
		},
	};

	// テーブル形式CSV読み込み用ランダム順序のテストデータ(空文字列はnull)
	static public final Object[][] readRandomTableAlgeSetData =
	{
		{
			new DtBase("基底08", "string" , "#", "#"), "文字列08",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-0.2108"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底02", "string" , "#", "#"), "!%!%!%文字列02",
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("123.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
			new DtBase("基底06", "string" , "#", "#"), " !%文字列06",
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("-1006"),
			new DtBase("基底06", "boolean", "#", "#"), false,
			new DtBase("基底04", "string" , "#", "#"), "文字列!%04",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-975.04"),
			new DtBase("基底04", "boolean", "#", "#"), false,
			new DtBase("基底0c", "string" , "#", "#"), "!%n",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("1.12"),
			new DtBase("基底0c", "boolean", "#", "#"), true,
			new DtBase("基底0b", "string" , "#", "#"), null,
			new DtBase("基底0b", "decimal", "#", "#"), BigDecimal.ZERO,
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
		},
		{
			new DtBase("基底0d", "string" , "#", "#"), "!%!%文字列1d",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), true,
			new DtBase("基底0b", "string" , "#", "#"), "!%",
			new DtBase("基底0b", "decimal", "#", "#"), new BigDecimal("1.11"),
			new DtBase("基底0b", "boolean", "#", "#"), true,
			new DtBase("基底03", "string" , "#", "#"), "文字列13",
			new DtBase("基底03", "decimal", "#", "#"), new BigDecimal("1.03"),
			new DtBase("基底03", "boolean", "#", "#"), false,
			new DtBase("基底09", "string" , "#", "#"), "文字列19",
			new DtBase("基底09", "decimal", "#", "#"), new BigDecimal("1.09"),
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底07", "string" , "#", "#"), "文字列17",
			new DtBase("基底07", "decimal", "#", "#"), new BigDecimal("1.07"),
			new DtBase("基底07", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), "文字列15",
			new DtBase("基底05", "decimal", "#", "#"), new BigDecimal("1.05"),
			new DtBase("基底05", "boolean", "#", "#"), false,
			new DtBase("基底01", "string" , "#", "#"), "文字列11",
			new DtBase("基底01", "decimal", "#", "#"), new BigDecimal("1.01"),
			new DtBase("基底01", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底08", "string" , "#", "#"), "文字列28",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-2.08"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%!%文字列2d",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-2.13"),
			new DtBase("基底0d", "boolean", "#", "#"), null,
			new DtBase("基底04", "string" , "#", "#"), " !%文字列24",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-2.04"),
			new DtBase("基底04", "boolean", "#", "#"), true,
			new DtBase("基底0c", "string" , "#", "#"), "!%文字列2c",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("-2.12"),
			new DtBase("基底0c", "boolean", "#", "#"), false,
			new DtBase("基底0b", "string" , "#", "#"), "文字列2b",
			new DtBase("基底0b", "decimal", "#", "#"), new BigDecimal("-2.11"),
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底03", "string" , "#", "#"), "文字列23",
			new DtBase("基底03", "decimal", "#", "#"), new BigDecimal("-2.03"),
			new DtBase("基底03", "boolean", "#", "#"), true,
			new DtBase("基底07", "string" , "#", "#"), "文字列!%27",
			new DtBase("基底07", "decimal", "#", "#"), new BigDecimal("-2.07"),
			new DtBase("基底07", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底02", "string" , "#", "#"), null,
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("3.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), null,
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("3.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
			new DtBase("基底06", "string" , "#", "#"), null,
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("3.06"),
			new DtBase("基底06", "boolean", "#", "#"), true,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), new BigDecimal("3.10"),
			new DtBase("基底0a", "boolean", "#", "#"), false,
			new DtBase("基底09", "string" , "#", "#"), null,
			new DtBase("基底09", "decimal", "#", "#"), new BigDecimal("3.09"),
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), null,
			new DtBase("基底05", "decimal", "#", "#"), new BigDecimal("3.05"),
			new DtBase("基底05", "boolean", "#", "#"), true,
			new DtBase("基底01", "string" , "#", "#"), null,
			new DtBase("基底01", "decimal", "#", "#"), new BigDecimal("3.01"),
			new DtBase("基底01", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底02", "string" , "#", "#"), "文字列42",
			new DtBase("基底02", "decimal", "#", "#"), null,
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底09", "string" , "#", "#"), "文字列49",
			new DtBase("基底09", "decimal", "#", "#"), null,
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), "文字列45",
			new DtBase("基底05", "decimal", "#", "#"), null,
			new DtBase("基底05", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底08", "string" , "#", "#"), null,
			new DtBase("基底08", "decimal", "#", "#"), null,
			new DtBase("基底08", "boolean", "#", "#"), null,
			new DtBase("基底0d", "string" , "#", "#"), null,
			new DtBase("基底0d", "decimal", "#", "#"), null,
			new DtBase("基底0d", "boolean", "#", "#"), null,
			new DtBase("基底0b", "string" , "#", "#"), null,
			new DtBase("基底0b", "decimal", "#", "#"), null,
			new DtBase("基底0b", "boolean", "#", "#"), null,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
			new DtBase("基底03", "string" , "#", "#"), null,
			new DtBase("基底03", "decimal", "#", "#"), null,
			new DtBase("基底03", "boolean", "#", "#"), null,
			new DtBase("基底07", "string" , "#", "#"), null,
			new DtBase("基底07", "decimal", "#", "#"), null,
			new DtBase("基底07", "boolean", "#", "#"), null,
			new DtBase("基底01", "string" , "#", "#"), null,
			new DtBase("基底01", "decimal", "#", "#"), null,
			new DtBase("基底01", "boolean", "#", "#"), null,
		},
		{
			new DtBase("基底08", "string" , "#", "#"), "文字列08",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-0.2108"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底02", "string" , "#", "#"), "!%!%!%文字列02",
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("123.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
			new DtBase("基底06", "string" , "#", "#"), " !%文字列06",
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("-1006"),
			new DtBase("基底06", "boolean", "#", "#"), false,
			new DtBase("基底04", "string" , "#", "#"), "文字列!%04",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-975.04"),
			new DtBase("基底04", "boolean", "#", "#"), false,
			new DtBase("基底0c", "string" , "#", "#"), "!%n",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("1.12"),
			new DtBase("基底0c", "boolean", "#", "#"), true,
			new DtBase("基底0b", "string" , "#", "#"), null,
			new DtBase("基底0b", "decimal", "#", "#"), BigDecimal.ZERO,
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
		},
	};

	// 基準となる全ソート済みテストデータ(空文字列も含む)
	static public final Object[][] readSortedAlgeSetData =
	{
		{
			new DtBase("基底02", "string" , "#", "#"), "!%!%!%文字列02",
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("123.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底04", "string" , "#", "#"), "文字列!%04",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-975.04"),
			new DtBase("基底04", "boolean", "#", "#"), false,
			new DtBase("基底06", "string" , "#", "#"), " !%文字列06",
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("-1006"),
			new DtBase("基底06", "boolean", "#", "#"), false,
			new DtBase("基底08", "string" , "#", "#"), "文字列08",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-0.2108"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
			new DtBase("基底0b", "string" , "#", "#"), null,
			new DtBase("基底0b", "decimal", "#", "#"), BigDecimal.ZERO,
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底0c", "string" , "#", "#"), "!%n",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("1.12"),
			new DtBase("基底0c", "boolean", "#", "#"), true,
			new DtBase("基底0d", "string" , "#", "#"), "!%",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底01", "string" , "#", "#"), "文字列11",
			new DtBase("基底01", "decimal", "#", "#"), new BigDecimal("1.01"),
			new DtBase("基底01", "boolean", "#", "#"), false,
			new DtBase("基底03", "string" , "#", "#"), "文字列13",
			new DtBase("基底03", "decimal", "#", "#"), new BigDecimal("1.03"),
			new DtBase("基底03", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), "文字列15",
			new DtBase("基底05", "decimal", "#", "#"), new BigDecimal("1.05"),
			new DtBase("基底05", "boolean", "#", "#"), false,
			new DtBase("基底07", "string" , "#", "#"), "文字列17",
			new DtBase("基底07", "decimal", "#", "#"), new BigDecimal("1.07"),
			new DtBase("基底07", "boolean", "#", "#"), false,
			new DtBase("基底09", "string" , "#", "#"), "文字列19",
			new DtBase("基底09", "decimal", "#", "#"), new BigDecimal("1.09"),
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底0b", "string" , "#", "#"), "!%",
			new DtBase("基底0b", "decimal", "#", "#"), new BigDecimal("1.11"),
			new DtBase("基底0b", "boolean", "#", "#"), true,
			new DtBase("基底0d", "string" , "#", "#"), "!%!%文字列1d",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), true,
		},
		{
			new DtBase("基底03", "string" , "#", "#"), "文字列23",
			new DtBase("基底03", "decimal", "#", "#"), new BigDecimal("-2.03"),
			new DtBase("基底03", "boolean", "#", "#"), true,
			new DtBase("基底04", "string" , "#", "#"), " !%文字列24",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-2.04"),
			new DtBase("基底04", "boolean", "#", "#"), true,
			new DtBase("基底07", "string" , "#", "#"), "文字列!%27",
			new DtBase("基底07", "decimal", "#", "#"), new BigDecimal("-2.07"),
			new DtBase("基底07", "boolean", "#", "#"), false,
			new DtBase("基底08", "string" , "#", "#"), "文字列28",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-2.08"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底0b", "string" , "#", "#"), "文字列2b",
			new DtBase("基底0b", "decimal", "#", "#"), new BigDecimal("-2.11"),
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底0c", "string" , "#", "#"), "!%文字列2c",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("-2.12"),
			new DtBase("基底0c", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%!%文字列2d",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-2.13"),
			new DtBase("基底0d", "boolean", "#", "#"), null,
		},
		{
			new DtBase("基底01", "string" , "#", "#"), null,
			new DtBase("基底01", "decimal", "#", "#"), new BigDecimal("3.01"),
			new DtBase("基底01", "boolean", "#", "#"), false,
			new DtBase("基底02", "string" , "#", "#"), null,
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("3.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), null,
			new DtBase("基底05", "decimal", "#", "#"), new BigDecimal("3.05"),
			new DtBase("基底05", "boolean", "#", "#"), true,
			new DtBase("基底06", "string" , "#", "#"), null,
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("3.06"),
			new DtBase("基底06", "boolean", "#", "#"), true,
			new DtBase("基底09", "string" , "#", "#"), null,
			new DtBase("基底09", "decimal", "#", "#"), new BigDecimal("3.09"),
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), new BigDecimal("3.10"),
			new DtBase("基底0a", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), null,
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("3.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底02", "string" , "#", "#"), "文字列42",
			new DtBase("基底02", "decimal", "#", "#"), null,
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), "文字列45",
			new DtBase("基底05", "decimal", "#", "#"), null,
			new DtBase("基底05", "boolean", "#", "#"), false,
			new DtBase("基底09", "string" , "#", "#"), "文字列49",
			new DtBase("基底09", "decimal", "#", "#"), null,
			new DtBase("基底09", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底01", "string" , "#", "#"), null,
			new DtBase("基底01", "decimal", "#", "#"), null,
			new DtBase("基底01", "boolean", "#", "#"), null,
			new DtBase("基底03", "string" , "#", "#"), null,
			new DtBase("基底03", "decimal", "#", "#"), null,
			new DtBase("基底03", "boolean", "#", "#"), null,
			new DtBase("基底07", "string" , "#", "#"), null,
			new DtBase("基底07", "decimal", "#", "#"), null,
			new DtBase("基底07", "boolean", "#", "#"), null,
			new DtBase("基底08", "string" , "#", "#"), null,
			new DtBase("基底08", "decimal", "#", "#"), null,
			new DtBase("基底08", "boolean", "#", "#"), null,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
			new DtBase("基底0b", "string" , "#", "#"), null,
			new DtBase("基底0b", "decimal", "#", "#"), null,
			new DtBase("基底0b", "boolean", "#", "#"), null,
			new DtBase("基底0d", "string" , "#", "#"), null,
			new DtBase("基底0d", "decimal", "#", "#"), null,
			new DtBase("基底0d", "boolean", "#", "#"), null,
		},
		{
			new DtBase("基底02", "string" , "#", "#"), "!%!%!%文字列02",
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("123.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底04", "string" , "#", "#"), "文字列!%04",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-975.04"),
			new DtBase("基底04", "boolean", "#", "#"), false,
			new DtBase("基底06", "string" , "#", "#"), " !%文字列06",
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("-1006"),
			new DtBase("基底06", "boolean", "#", "#"), false,
			new DtBase("基底08", "string" , "#", "#"), "文字列08",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-0.2108"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
			new DtBase("基底0b", "string" , "#", "#"), null,
			new DtBase("基底0b", "decimal", "#", "#"), BigDecimal.ZERO,
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底0c", "string" , "#", "#"), "!%n",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("1.12"),
			new DtBase("基底0c", "boolean", "#", "#"), true,
			new DtBase("基底0d", "string" , "#", "#"), "!%",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
		},
	};

	// 基準となる部分ソート済みテストデータ(空文字列も含む)
	static public final Object[][] readHalfSortedAlgeSetData =
	{
		{
			new DtBase("基底02", "string" , "#", "#"), "!%!%!%文字列02",
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("123.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底04", "string" , "#", "#"), "文字列!%04",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-975.04"),
			new DtBase("基底04", "boolean", "#", "#"), false,
			new DtBase("基底06", "string" , "#", "#"), " !%文字列06",
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("-1006"),
			new DtBase("基底06", "boolean", "#", "#"), false,
			new DtBase("基底08", "string" , "#", "#"), "文字列08",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-0.2108"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
			new DtBase("基底0c", "string" , "#", "#"), "!%n",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("1.12"),
			new DtBase("基底0c", "boolean", "#", "#"), true,
			new DtBase("基底0b", "string" , "#", "#"), null,
			new DtBase("基底0b", "decimal", "#", "#"), BigDecimal.ZERO,
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
		},
		{
			new DtBase("基底01", "string" , "#", "#"), "文字列11",
			new DtBase("基底01", "decimal", "#", "#"), new BigDecimal("1.01"),
			new DtBase("基底01", "boolean", "#", "#"), false,
			new DtBase("基底03", "string" , "#", "#"), "文字列13",
			new DtBase("基底03", "decimal", "#", "#"), new BigDecimal("1.03"),
			new DtBase("基底03", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), "文字列15",
			new DtBase("基底05", "decimal", "#", "#"), new BigDecimal("1.05"),
			new DtBase("基底05", "boolean", "#", "#"), false,
			new DtBase("基底07", "string" , "#", "#"), "文字列17",
			new DtBase("基底07", "decimal", "#", "#"), new BigDecimal("1.07"),
			new DtBase("基底07", "boolean", "#", "#"), false,
			new DtBase("基底09", "string" , "#", "#"), "文字列19",
			new DtBase("基底09", "decimal", "#", "#"), new BigDecimal("1.09"),
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%!%文字列1d",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), true,
			new DtBase("基底0b", "string" , "#", "#"), "!%",
			new DtBase("基底0b", "decimal", "#", "#"), new BigDecimal("1.11"),
			new DtBase("基底0b", "boolean", "#", "#"), true,
		},
		{
			new DtBase("基底03", "string" , "#", "#"), "文字列23",
			new DtBase("基底03", "decimal", "#", "#"), new BigDecimal("-2.03"),
			new DtBase("基底03", "boolean", "#", "#"), true,
			new DtBase("基底04", "string" , "#", "#"), " !%文字列24",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-2.04"),
			new DtBase("基底04", "boolean", "#", "#"), true,
			new DtBase("基底07", "string" , "#", "#"), "文字列!%27",
			new DtBase("基底07", "decimal", "#", "#"), new BigDecimal("-2.07"),
			new DtBase("基底07", "boolean", "#", "#"), false,
			new DtBase("基底08", "string" , "#", "#"), "文字列28",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-2.08"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%!%文字列2d",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-2.13"),
			new DtBase("基底0d", "boolean", "#", "#"), null,
			new DtBase("基底0c", "string" , "#", "#"), "!%文字列2c",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("-2.12"),
			new DtBase("基底0c", "boolean", "#", "#"), false,
			new DtBase("基底0b", "string" , "#", "#"), "文字列2b",
			new DtBase("基底0b", "decimal", "#", "#"), new BigDecimal("-2.11"),
			new DtBase("基底0b", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底01", "string" , "#", "#"), null,
			new DtBase("基底01", "decimal", "#", "#"), new BigDecimal("3.01"),
			new DtBase("基底01", "boolean", "#", "#"), false,
			new DtBase("基底02", "string" , "#", "#"), null,
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("3.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), null,
			new DtBase("基底05", "decimal", "#", "#"), new BigDecimal("3.05"),
			new DtBase("基底05", "boolean", "#", "#"), true,
			new DtBase("基底06", "string" , "#", "#"), null,
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("3.06"),
			new DtBase("基底06", "boolean", "#", "#"), true,
			new DtBase("基底09", "string" , "#", "#"), null,
			new DtBase("基底09", "decimal", "#", "#"), new BigDecimal("3.09"),
			new DtBase("基底09", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), null,
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("3.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), new BigDecimal("3.10"),
			new DtBase("基底0a", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底02", "string" , "#", "#"), "文字列42",
			new DtBase("基底02", "decimal", "#", "#"), null,
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底05", "string" , "#", "#"), "文字列45",
			new DtBase("基底05", "decimal", "#", "#"), null,
			new DtBase("基底05", "boolean", "#", "#"), false,
			new DtBase("基底09", "string" , "#", "#"), "文字列49",
			new DtBase("基底09", "decimal", "#", "#"), null,
			new DtBase("基底09", "boolean", "#", "#"), false,
		},
		{
			new DtBase("基底01", "string" , "#", "#"), null,
			new DtBase("基底01", "decimal", "#", "#"), null,
			new DtBase("基底01", "boolean", "#", "#"), null,
			new DtBase("基底03", "string" , "#", "#"), null,
			new DtBase("基底03", "decimal", "#", "#"), null,
			new DtBase("基底03", "boolean", "#", "#"), null,
			new DtBase("基底07", "string" , "#", "#"), null,
			new DtBase("基底07", "decimal", "#", "#"), null,
			new DtBase("基底07", "boolean", "#", "#"), null,
			new DtBase("基底08", "string" , "#", "#"), null,
			new DtBase("基底08", "decimal", "#", "#"), null,
			new DtBase("基底08", "boolean", "#", "#"), null,
			new DtBase("基底0d", "string" , "#", "#"), null,
			new DtBase("基底0d", "decimal", "#", "#"), null,
			new DtBase("基底0d", "boolean", "#", "#"), null,
			new DtBase("基底0b", "string" , "#", "#"), null,
			new DtBase("基底0b", "decimal", "#", "#"), null,
			new DtBase("基底0b", "boolean", "#", "#"), null,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
		},
		{
			new DtBase("基底02", "string" , "#", "#"), "!%!%!%文字列02",
			new DtBase("基底02", "decimal", "#", "#"), new BigDecimal("123.02"),
			new DtBase("基底02", "boolean", "#", "#"), false,
			new DtBase("基底04", "string" , "#", "#"), "文字列!%04",
			new DtBase("基底04", "decimal", "#", "#"), new BigDecimal("-975.04"),
			new DtBase("基底04", "boolean", "#", "#"), false,
			new DtBase("基底06", "string" , "#", "#"), " !%文字列06",
			new DtBase("基底06", "decimal", "#", "#"), new BigDecimal("-1006"),
			new DtBase("基底06", "boolean", "#", "#"), false,
			new DtBase("基底08", "string" , "#", "#"), "文字列08",
			new DtBase("基底08", "decimal", "#", "#"), new BigDecimal("-0.2108"),
			new DtBase("基底08", "boolean", "#", "#"), false,
			new DtBase("基底0d", "string" , "#", "#"), "!%",
			new DtBase("基底0d", "decimal", "#", "#"), new BigDecimal("-1.13"),
			new DtBase("基底0d", "boolean", "#", "#"), false,
			new DtBase("基底0c", "string" , "#", "#"), "!%n",
			new DtBase("基底0c", "decimal", "#", "#"), new BigDecimal("1.12"),
			new DtBase("基底0c", "boolean", "#", "#"), true,
			new DtBase("基底0b", "string" , "#", "#"), null,
			new DtBase("基底0b", "decimal", "#", "#"), BigDecimal.ZERO,
			new DtBase("基底0b", "boolean", "#", "#"), false,
			new DtBase("基底0a", "string" , "#", "#"), null,
			new DtBase("基底0a", "decimal", "#", "#"), null,
			new DtBase("基底0a", "boolean", "#", "#"), null,
		},
	};

	//------------------------------------------------------------
	// Fields
	//------------------------------------------------------------

	//------------------------------------------------------------
	// Constructions
	//------------------------------------------------------------

	//------------------------------------------------------------
	// Public interfaces
	//------------------------------------------------------------
	
	static public DtAlgeSet removeNullElements(DtAlgeSet algeset) {
		DtAlgeSet retset = new DtAlgeSet(algeset.size());
		for (Dtalge alge : algeset) {
			retset.add(alge.nonullProjection());
		}
		return retset;
	}
	
	static public Collection<Dtalge> makeDtalges(Object[]...algeElements) {
		ArrayList<Dtalge> list = new ArrayList<Dtalge>();
		for (Object[] elem : algeElements) {
			Dtalge alge = null;
			if (elem != null) {
				alge = new Dtalge(elem);
			}
			list.add(alge);
		}
		return list;
	}
	
	static public boolean equalElementSequence(DtAlgeSet aset, Object[][] elements) {
		if (elements == null || elements.length < 1) {
			return (aset == null ? true : aset.isEmpty());
		}
		
		if (aset.size() != elements.length)
			return false;
		
		int index = 0;
		for (Dtalge alge : aset) {
			if (!DtalgeIOTestHelper.equalElementSequence(alge, elements[index])) {
				System.err.println("DtAlgeSetTest : equalElementSequence : [" + index + "]");
				return false;
			}
			index++;
		}
		return true;
	}
	
	static public boolean equalNoNullElementSequence(DtAlgeSet aset, Object[][] elements) {
		if (elements == null || elements.length < 1) {
			return (aset == null ? true : aset.isEmpty());
		}
		
		if (aset.size() != elements.length)
			return false;
		
		int index = 0;
		for (Dtalge alge : aset) {
			if (!DtalgeIOTestHelper.equalNoNullElementSequence(alge, elements[index])) {
				System.err.println("DtAlgeSetTest : equalElementSequence : [" + index + "]");
				return false;
			}
			index++;
		}
		return true;
	}

	//------------------------------------------------------------
	// Internal methods
	//------------------------------------------------------------

	//------------------------------------------------------------
	// Inner classes
	//------------------------------------------------------------
}
