<?xml version="1.0" encoding="UTF-8"?>
<project name="aadlc" default="create" basedir=".">
	<property name="dist.dir" location="${basedir}/jar" />
	<property name="build.dir" location="${dist.dir}/classes" />
	<property name="src.dir" location="${basedir}/java" />
	<property name="lib.dir" location="${basedir}/lib" />
	<property name="resource.dir" location="${basedir}/resource" />
	<property name="main.class" value="ssac.aadlc.Main" />
	<property name="aadlrt.build.dir" location="${dist.dir}/runtime" />
	<property name="aadlrt.src.dir" location="${basedir}/runtime" />
	<property name="jlibsinjar.build.dir" location="${dist.dir}/jlibsinjar" />
	<property name="jlibsinjar.src.dir" location="${basedir}/jlibsinjar" />

	<path id="lib.path">
		<fileset dir="${lib.dir}">
			<include name="**/*.jar" />
		</fileset>
	</path>

	<!--init property-->
	<target name="init" >
		<property name="dist.title" value="AADL Compiler" />
		<property name="dist.short.version" value="4.0.0" />
		<property name="dist.version" value="${dist.short.version}.20210831" />
		<property name="dist.name" value="aadlc" />
		<property name="aadlrt.title" value="AADL Runtime library" />
		<property name="aadlrt.short.version" value="4.0.0" />
		<property name="aadlrt.version" value="${aadlrt.short.version}.20210831" />
		<property name="aadlrt.name" value="aadlrt" />
		<property name="jlibsinjar.title" value="Libraries-in-jar utility" />
		<property name="jlibsinjar.name" value="aadl-libsinjar-util" />
		<mkdir dir="${dist.dir}" />
	</target>

	<!--build classes-->
	<!-- for AADL Runtime library -->
	<target name="mkrtclass" depends="init">
		<!-- create directory -->
		<mkdir dir="${aadlrt.build.dir}" />
		
		<!-- compile -->
		<!-- javac destdir="${aadlrt.build.dir}" includeantruntime="no" fork="yes" compiler="javac1.6" encoding="UTF8" source="1.6" -->
		<javac destdir="${aadlrt.build.dir}" includeantruntime="no" fork="yes" compiler="javac10+" encoding="UTF8" source="11">
			<compilerarg line="-deprecation -g:lines,source" />
			<classpath refid="lib.path" />
			<src path="${aadlrt.src.dir}" />
		</javac>
	</target>
	<!-- for AADL Compiler -->
	<target name="mkclass" depends="init">
		<!-- create directory -->
		<mkdir dir="${build.dir}" />
		
		<!-- compile -->
		<!-- javac destdir="${build.dir}" includeantruntime="no" fork="yes" compiler="javac1.6" encoding="UTF8" source="1.6" -->
		<javac destdir="${build.dir}" includeantruntime="no" fork="yes" compiler="javac10+" encoding="UTF8" source="11">
			<compilerarg line="-deprecation -g:lines,source" />
			<classpath refid="lib.path" />
			<classpath path="${aadlrt.build.dir}" />
			<src path="${src.dir}" />
			<src path="${jlibsinjar.src.dir}" />
		</javac>
	</target>
	<!-- for Libs-in-jar utility 
	<target name="mklijclass" depends="init">
		- - create directory - -
		<mkdir dir="${jlibsinjar.build.dir}" />
		
		- - compile - -
		<javac destdir="${jlibsinjar.build.dir}" includeantruntime="no" fork="yes" compiler="javac10+" encoding="UTF8" source="11">
			<compilerarg line="-deprecation -g:lines,source" />
			<src path="${jlibsinjar.src.dir}" />
		</javac>
	</target>
	-->

	<!-- create -->
	<target name="create" depends="mkrtclass, mkclass">
		<!-- create directories -->
		<mkdir dir="${dist.dir}/lib" />
		<!-- copy libraries -->
		<copy todir="${dist.dir}/lib">
			<fileset dir="${lib.dir}">
				<include name="**/Dtalge*.jar" />
				<include name="**/Exalge*.jar" />
				<include name="**/antlr-runtime-*.jar" />
				<include name="**/mqttutil*.jar" />
				<include name="**/mongo-*.jar" />
			</fileset>
		</copy>
		<!-- create jar file (Libs-in-jar util)
		<jar destfile="${dist.dir}/lib/${jlibsinjar.name}.jar" basedir="${jlibsinjar.build.dir}">
			<manifest>
				<attribute name="Specification-Title" value="${jlibsinjar.title}" />
				<attribute name="Specification-Version" value="${dist.version}" />
				<attribute name="Implementation-Title" value="${jlibsinjar.title}" />
				<attribute name="Implementation-Version" value="${dist.version}" />
			</manifest>
		</jar -->
		<!-- create jar file (AADL Runtime) -->
		<jar destfile="${dist.dir}/lib/${aadlrt.name}.jar" basedir="${aadlrt.build.dir}">
			<manifest>
				<attribute name="Specification-Title" value="${aadlrt.title}" />
				<attribute name="Specification-Version" value="${aadlrt.version}" />
				<attribute name="Implementation-Title" value="${aadlrt.title}" />
				<attribute name="Implementation-Version" value="${aadlrt.version}" />
			</manifest>
		</jar>
		<!-- create jar file (AADL Compiler) -->
		<jar destfile="${dist.dir}/lib/${dist.name}.jar" basedir="${build.dir}">
			<manifest>
				<attribute name="Specification-Title" value="${dist.title}" />
				<attribute name="Specification-Version" value="${dist.version}" />
				<attribute name="Implementation-Title" value="${dist.title}" />
				<attribute name="Implementation-Version" value="${dist.version}" />
				<attribute name="Main-Class" value="${main.class}" />
			</manifest>
		</jar>
		
		<!-- create javadoc zip
		<zip destfile="${dist.dir}/${dist.name}-${dist.version}-javadoc.zip">
			<fileset dir="${doc.dir}/javadoc" />
		</zip>
		-->
		
		<!-- create sources zip -->
		<zip destfile="${dist.dir}/${dist.name}-${dist.short.version}-src.zip">
			<fileset dir="${basedir}/">
				<include name="java/" />
				<include name="jlibsinjar/" />
				<include name="runtime/" />
				<include name="recource/" />
				<include name="grammar/AADL.g" />
				<include name="grammar/AADLWalker.g" />
				<include name="grammar/grammarBuild.bat" />
				<include name="grammar/walkerBuild.bat" />
				<include name="lib/*.jar" />
				<include name="lib_src/*" />
			</fileset>
			<fileset file="${basedir}/build.xml" />
			<fileset file="${basedir}/Changes_ja.txt" />
			<fileset file="${basedir}/LICENSE" />
			<fileset file="${basedir}/LICENSE.antlr" />
		</zip>
	</target>

	<!-- clean -->
	<target name="clean" depends="init">
		<delete dir="${build.dir}" />
		<delete dir="${dist.dir}/lib" />
		<delete file="${dist.dir}/${dist.name}-*-src.zip" />
	</target>

</project>
